image: fedora:39

meson-build:
    script:
    - dnf -y install dnf-plugins-core
    - dnf -y groupinstall buildsys-build
    - dnf -y builddep pixman
    - dnf -y install meson
    - meson setup build
    - ninja -C build test
